scan_to_scan_filter_chain:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        min_x: -0.3
        max_x:  0.3
        min_y: -0.3
        max_y:  0.3
        min_z: -1.0
        max_z:  1.0
        
        invert: false # activate to remove all points outside of the box
    filter2: 
      name: angular_bounds_filter
      type: laser_filters/LaserScanAngularBoundsFilter
      params: 
        # 250 deg
        lower_angle: -2.0944
        upper_angle:  2.0944